steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mi-servicio', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mi-servicio']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'mi-servicio',
      '--image=gcr.io/$PROJECT_ID/mi-servicio',
      '--region=us-central1',
      '--platform=managed',
      '--allow-unauthenticated',
      '--timeout=600',
      '--memory=8Gi' 
    ]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
